### ISSUE TITLE
Amend CSS Asset reference to LESS

### ISSUE THREAD

**Issue by daviddarnes** [basekit/docs.basekit.com#103]
`.css` files cannot be used in templates, they have to be renamed `.less`.

Reference link: http://docs.basekit.com/templating/assets/

**Comment by daviddarnes** [comment]
Update: this is still true. It understands CSS, just not the file format. There's no option to include a `.css` file:

- `stylesheet.less` is imported using the `headScript` code, so you can't change the import path
- Using using the `asset()` path with `<link>` to import a `.css` file doesn't seem to work
- Using a `.less` file to import a `.css` file doesn't seem to work either

**Comment by daviddarnes** [comment]
@dominic-hickey did this ever get resolved? At the minute the documentation is stating something that for some reason isn't possible in the TDK or the editor as far as I'm aware.

**Comment by dominic-hickey** [comment]
@daviddarnes not sure to be honest. I think I created a ticket but it's probably lost in the back log somewhere. I'll try and track it down.

**Comment by daviddarnes** [comment]
@dominic-hickey thanks, I think I spoke with @richardhealy about it as well.

**Comment by daviddarnes** [comment]
Did this ever get fixed @dominic-hickey?

**Comment by daviddarnes** [comment]
Using a regular `<link>` import with a `.css` works, but it doesn't work as an import. Consider this fixed to the best of our ability
