### ISSUE TITLE
Dropbox Button

### ISSUE THREAD

**Issue by MartaGonzalez** [basekit/docs.basekit.com#121]
1) When I use this widget in my template as it shows in the ‘Example Usage’ section the button only displays the dropbox icon but no text. Not sure whether it is missing the option to set up the button ‘text’?

2) Also the alignment in the 'Example Usage' is different from the one in the ‘Widget Options':
'align': 'left',
or
'align': 'widget-align-left’
which one is correct?

**Comment by daviddarnes** [comment]
@MartaGonzalez my mistake, it should have been `widget-align-left`. I've amended it now, but it appears it can be any class that's used here https://github.com/basekit/basekit/blob/809248a1ad2955efdbf887a7487ae92381a78753/templates/common/bk-less-framework-v8.less#L998-L1030
