### ISSUE TITLE
Facebook Like

### ISSUE THREAD

**Issue by MartaGonzalez** [basekit/docs.basekit.com#122]
Not sure whether the info in http://docs.basekit.com/widgets/v2/facebook-like/ is up-to-date. 

When I used this widget in my template some of the options didn't seem to work in the TDK.

1) I’ve tried to use the option for ’text’ that shows in the ‘Example Usage’ but cannot see the text in the Facebook button in the TDK. And there is no option to set up the ‘text’ in the editor (v8) at the moment.

2) The ‘layout’ options are different in the ‘Widget Options’ section and in the editor. It says standard, button_count, box_count in the editor, and standard, horizontal, vertical in the widget options.

3) When using the ‘og_image’ option nothing showed in the TDK. In the editor no image showed when adding an image to the ‘Image Displayed’ option.

4) I haven't been able to use the options ‘og_title’ and ‘og_description’ either.

**Comment by daviddarnes** [comment]
@MartaGonzalez hmm, I can see why `text` doesn't actually do anything but I don't know about the rest of the options. I've attempted to remove and update what I can. As for the layout options, the codebase appears to correspond like so:

- Standard = `standard`
- Horizontal = `button_count`
- Vertical = `box_count`

Do these options not work in the TDK?

**Comment by daviddarnes** [comment]
@MartaGonzalez check out the updated options here, could you check if they all work in the TDK? https://github.com/basekit/docs.basekit.com/blob/master/widgets/v2/facebook-like.md#widget-options

**Comment by MartaGonzalez** [comment]
@daviddarnes I've tried using the updated widget and it doesn't display in the TDK. When I inspected it I could see that the widget was in the markup but it doesn't display for some reason.

**Comment by daviddarnes** [comment]
@MartaGonzalez hmm that's weird, could you find out if the Facebook like button works ok in the TDK? Just incase it's a bug.

**Comment by MartaGonzalez** [comment]
@daviddarnes Yup, it works in the TDK when it's part of the {{zone('main')|raw}} but not when you bake it in the template using {{widget('facebooklike', 'likebutton', { showFaces: 'true', action: 'like', colorscheme: 'light', layout: 'standard', height: '80', font: 'arial', locale: 'en_US', thisUrl: 'www.mysite.com' })|raw}
Apparently FB won't work in the TDK if you bake it in, Hao can explain this.

**Comment by daviddarnes** [comment]
@MartaGonzalez ah right I see. So to clarify, the Facebook like button does work but it doesn't work when viewing it in the TDK after baking it in. Is that right @bkhaochang?

**Comment by bkhaochang** [comment]
Hmm the widget cannot be used as a template widget but it can be loaded in TDK in the main zone.

**Comment by daviddarnes** [comment]
@bkhaochang oh, does that mean developers won't be able to add it into a custom template?

**Comment by bkhaochang** [comment]
Yep it cannot be added/baked into template.

**Comment by daviddarnes** [comment]
Oh, in that case maybe we shouldn't have it in the documentation. If people can't code it in then we shouldn't show it 😟

**Comment by bkhaochang** [comment]
Good point!

**Comment by dominic-hickey** [comment]
We either remove it from the docs, or add a warning at the top of the page - saying it's a zone widget only. That way at least developers will know it exists.

**Comment by daviddarnes** [comment]
@dominic-hickey I like your thinking! I'll adjust the page accordingly. We can still provide the markup as it might be useful for styling purposes.

**Comment by daviddarnes** [comment]
See screenshot
![screen shot 2016-04-12 at 15 35 54](https://cloud.githubusercontent.com/assets/1177460/14463747/3b7dcab6-00c4-11e6-835f-d534ada09ca5.png)

**Comment by dominic-hickey** [comment]
Maybe, "This widget is only available as a '[zone-widget](http://docs.basekit.com/widgets/#zone-widgets)', it cannot be baked in to a custom template. As of..."

**Comment by daviddarnes** [comment]
> **IMPORTANT:** This widget is only available as a 'zone-widget', it cannot be coded in to a custom template. As of **version 8.00 and above**.

👍 ❓
