### ISSUE TITLE
Featured Products & Ecommerce Categories Widgets don't work in the TDK

### ISSUE THREAD

**Issue by MartaGonzalez** [basekit/docs.basekit.com#125]
Featured Products:
When using the widget from the example usage in my template nothing shows in the TDK:
{{widget('ecomfeaturedproducts', 'featuredproducts', {})|raw}}

Ecommerce Categories:
The widget from the example usage seems to break the TDK. I've copied and pasted this widget into my template and the TDK went blank.
{{widget('ecomcategories', 'productcategories', {})|raw}}

**Comment by daviddarnes** [comment]
@MartaGonzalez hi Marta, do you know the right code that should be in the documentation? I can't really do much with this, TDK issues should really be reported in JIRA :/

**Comment by MartaGonzalez** [comment]
@daviddarnes Apparently the right code for the categories widget is:
{{widget('ecomcategorieslist', 'productcategories', {})|raw}}

The code for the featured products widget is right (It wasn't working in my site because of a js issue with my template).

Althought the two widgets work they won't display anything in the TDK (Hao can explain further)

**Comment by bkhaochang** [comment]
Yep those two widgets are plugin widgets which require the plugin(store) data.

If there isn't setting for those two widgets, in the Editor they will show some messages that you need to add product and set tags etc. But in the published site they will just do nothing.

TDK presents the widgets style in the published site so you will not see the widgets as a template widgets in this situation. :(

**Comment by daviddarnes** [comment]
@MartaGonzalez @bkhaochang thats fine, I've updated the page to reflect this. Could you just double check please? https://github.com/basekit/docs.basekit.com/blob/master/widgets/v2/ecommerce-categories.md#example-usage * Thanks for both your help!

_* Note: Ignore the `{% highlight python %} {% raw %}` stuff on the page, it's for the documentation site_
