### ISSUE TITLE
V8 Documentation Additions

### ISSUE THREAD

**Issue by daviddarnes** [basekit/docs.basekit.com#127]
- [ ] Create _'Getting Started with V8'_ section
  - [ ] Document and screenshot template tasks
  - [ ] Keep track of urls and make sure there are no conflicts
- [ ] Document new style Variables

_Note: Consult with template team on full differences between v7 and v8 templating_

**Comment by dominic-hickey** [comment]
- Getting Started
  - Local Development
  - Downloading a Template
  - Editing a Template
  - Uploading a Template
- Getting started with V8
  - Downloading a Template
  - Editing a Template
  - Uploading a Template
- Templating
  - Twig
  - Assets
  - JavaScript
  - Page Types
  - Metadata
  - LESS
  - Quality
- Templating with V8
  - Metadata 
  - LESS
  - Style variables
