### ISSUE TITLE
'Getting Started' - Pages Structure Rework

### ISSUE THREAD

**Issue by dominic-hickey** [basekit/docs.basekit.com#52]
### Downloading a Template
http://docs.basekit.com/getting-started/downloading/

### Issue
There is quite a lot of information on the page; and unlike others it does not provide a segregated, numbered approach that makes the content easier to read. 

### Task
Add numbered bullet points to the content

**Comment by daviddarnes** [comment]
This is more of an issue with the whole Getting Started section. Just applying headings to each section would improve a reader's digestion.

**Comment by daviddarnes** [comment]
Maybe @Kelz4848 could help in some way?

**Comment by richardhealy** [comment]
Can you ask her.

On 4 February 2015 at 10:42, David Darnes <notifications@github.com> wrote:

> Maybe @Kelz4848 <https://github.com/Kelz4848> could help in some way?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/basekit/docs.basekit.com/issues/52#issuecomment-72834060>
> .
>



-- 
*Richard Healy*
BaseKit Founder, VP of Technology & Design
Web:    www.basekit.com
e-mail:  richard.healy@basekit.com

**Comment by daviddarnes** [comment]
Pages in question:
* https://github.com/basekit/docs.basekit.com/blob/master/getting-started/downloading.md
* https://github.com/basekit/docs.basekit.com/blob/master/getting-started/editing.md
* https://github.com/basekit/docs.basekit.com/blob/master/getting-started/uploading.md

**Comment by daviddarnes** [comment]
Resolved in commits:
https://github.com/basekit/docs.basekit.com/commit/19b0a0be4cce77af4bb23a5b01de85347099754f
https://github.com/basekit/docs.basekit.com/commit/9a93a20b09b76980af0b4635015a1da54b03a66e
