### ISSUE TITLE
References to BaseKit on getting-started page

### ISSUE THREAD

**Issue by richardhealy** [basekit/docs.basekit.com#55]
We need to remove the following references:

- Access to BaseKit’s Editor --> Access to the Editor (same in the sidebar link)
- Access to BaseKit’s Theme Viewer --> Access the Local Theme Viewer
- Download our Template Development Kit needs to be Download the Theme Viewer (is this the right latest version?)

**Comment by daviddarnes** [comment]
As far as I'm aware this is the latest version.
"Template Development Kit" to "Theme Viewer"? Why not "Theme Development Kit"?
