### ISSUE TITLE
Include hide widget code

### ISSUE THREAD

**Issue by owenwas** [basekit/docs.basekit.com#68]
Add in the "showTplWidget":"0" code to hide a widget by default.

e.g.
{{widget('logo', 'logo', {"defaultlogo": asset('images/logo.png'),"showTplWidget":"0"})|raw}}

**Comment by daviddarnes** [comment]
@richardhealy do you know if this option works for _every_ widget?

**Comment by dominic-hickey** [comment]
@daviddarnes pretty sure it works for all standard widgets - not sure about the plugin widgets though?

**Comment by daviddarnes** [comment]
@dominic-hickey need this clarified so we're not giving false information.
