### ISSUE TITLE
Adds List of Font and Colour Variable Relationships

### ISSUE THREAD

**Issue by daviddarnes** [basekit/docs.basekit.com#76]
### Colour Swatches
- ```@color-swatch1```: Background
- ```@color-swatch2```: Contrast colour
- ```@color-swatch3```: Button colour
- ```@color-swatch4```: Title colour
- ```@color-swatch5```: Paragraph colour
- ```@color-swatch6```: Nav text colour
- ```@color-swatch7```: Header BG colour

### Font Swatches
- ```@font-swatch1```: Heading 1
- ```@font-swatch2```: Heading 2
- ```@font-swatch3```: Heading 3
- ```@font-swatch4```: Heading 4
- ```@font-swatch5```: Paragraph
- ```@font-swatch6```: Navigation Text
- ```@font-swatch7```: Buttons
- ```@font-swatch8```: Feature Title
- ```@font-swatch9```: Feature Subtitle
- ```@font-swatch10```: Company Name

**Comment by richardhealy** [comment]
Changed logo to company name

**Comment by daviddarnes** [comment]
@richardhealy huh? Is that related to this issue?

**Comment by richardhealy** [comment]
It was wrongly labelled. That swatch is meant for the Company Header....
not the Logo.

I did a search re: BaseKit Swatch Relationships and it comes up near the
top... so had to change it.

On 14 April 2015 at 23:35, David Darnes <notifications@github.com> wrote:

> @richardhealy <https://github.com/richardhealy> huh? Is that related to
> this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/basekit/docs.basekit.com/issues/76#issuecomment-93097543>
> .
>



-- 
*Richard Healy*
BaseKit Founder, VP of Technology & Design
Web:    www.basekit.com
e-mail:  richard.healy@basekit.com

**Comment by daviddarnes** [comment]
Ah that makes more sense, thanks!

**Comment by daviddarnes** [comment]
Added the references to the colour variables, font variables already had them. However this page could be broken down more and presented better. The colour and font variables within the Metadata are quite complex and couple be presented in more of a digestible manner. cc @ivan-basekit
