### ISSUE TITLE
Add custom fonts section

### ISSUE THREAD

**Issue by owenwas** [basekit/docs.basekit.com#84]
Can we add a section about adding custom fonts i.e font-face etc.

**Comment by daviddarnes** [comment]
@owenwas do you have an example? Adding custom fonts is just the same as adding it into any other site right?

**Comment by owenwas** [comment]
@daviddarnes I was referring to how to include font assets. A font-face generator will throw out standard css i.e 
src: url('/fonts/custom-webfont.eot');
src: url('/fonts/custom-webfont.eot?#iefix') format('embedded-opentype'),
etc.
etc.

So how do we include those assets in our template? -> switch 'url' to 'image' and include the font files in the structure as you normally would. I just think it would give any dev a helping hand if we have a little section relaying this info. What do you reckon?

**Comment by daviddarnes** [comment]
@owenwas yea, I can see how that could be useful. Not a super high priority though as it can be worked out. Definitely something to return to.
