### ISSUE TITLE
Add 'Page Title' widget

### ISSUE THREAD

**Issue by dominic-hickey** [basekit/docs.basekit.com#91]
There is a new 'page-title' widget that will be released with R58. There are no settings for this widget.

Widget code:

`{{widget('pagetitle', 'pagetitle-id', {})|raw}}`

**Comment by daviddarnes** [comment]
@dominic-hickey would this fall into Content & Images or Template Widgets? If it can be dragged in from the editor then technically it should be in Content & Images.
